### ISSUE TITLE
FR: Remove jQuery dependency

### ISSUE THREAD

**Issue by JiveDig** [WebberZone/top-10#138]
A client site is using this plugin, and all seems to work well, but it's the last plugin we have that relies on jQuery. In an age of performance, there doesn't seem to be a reason to require such a large library. It should be fairly straightforward to convert to vanilla JS with `fetch`. Thanks!

**Comment by ajaydsouza** [comment]
Thanks for this. JS isn’t my strong suit but I am definitely keen or removing the need for jQuery on the front end.

Have you tested the code above? I’m happy to give that a try as well.

**Comment by JiveDig** [comment]
Honestly it's not mine either, but I've done very similar a few times, changing from jQuery ajax to fetch. This may work as-is, but I haven't tested it.

Unrelated: Have you had any issues with this plugin on high-traffic sites? We were using a few other similar plugins/techniques for page views/counts and it choked out the server. I'm thinking we need some sort of ram/session/etc storage so it's not updating the DB on every page load.

**Comment by ajaydsouza** [comment]
I'll take a look. Going to need to learn to `fetch`.

On very high traffic sites, it could be an issue. I do have a rather optimised query to track but it does come down to server resources as it will hit the DB on each page load. The lists can be cached so that's not much of an issue.

One thing I have been contemplating is what you rightly point out on ram/session which I need to learn how to code in where it would write to DB only ever x seconds.

**Comment by JiveDig** [comment]
> One thing I have been contemplating is what you rightly point out on ram/session which I need to learn how to code in where it would write to DB only ever x seconds.

I plan to mess with this at some point and if I figure out before you I'll try to let you know my findings :)

**Comment by ajaydsouza** [comment]
Sounds good. ChatGPT thinks the code works and suggested a similar replacement to me as what you have above.

I'll give it a test drive and if it works put a beta in here.

**Comment by ajaydsouza** [comment]
I've now implemented the code to no longer require jQuery for the tracking script.
